/* SPDX-License-Identifier: GPL-2.0-or-later
 * Copyright 2021 Blender Foundation.
 */

/** \file
 * \ingroup bnpr
 *
 * Shader module that manage shader libraries, deferred compilation,
 * and static shader usage.
 */

#pragma once

#include <array>
#include <string>

#include "BLI_string_ref.hh"
#include "DRW_render.h"
#include "GPU_material.h"
#include "GPU_shader.h"


namespace blender::npr::strokegen {

/* Keep alphabetical order and clean prefix. */
enum eShaderType {
  COMPUTE_TEST = 0,
  DEPTH,
  POINTCLOUD_DEPTH,
  CURVES_DEPTH,
  DEPTH_CONSERVATIVE,
  POINTCLOUD_DEPTH_CONSERVATIVE,

  // Contour Edge Extraction & Rasterization
  GPU_MESHING_BOOSTRAP, 
  CONTOUR_GEOM_EXTRACT,
  CONTOUR_GEOM_EXTRACT_IBO_16BIT,
  FILL_DRAW_ARGS_CONTOUR_EDGES,
  FILL_DISPATCH_ARGS_CONTOUR_EDGES, 
  COMPUTE_CONTOUR_EDGE_RASTER_DATA, 
  INDIRECT_DRAW_CONTOUR_EDGES,

  // Contour Pixel Extraction (WIP)
  CONTOUR_PIXEL_COMPRESS,
  CONTOUR_PIXEL_COMPRESS_DBG,
  // CONTOUR_PIXEL_AND_EDGE_COLLECT

  // GPU Meshing Experiment
  MESH_COLLECT_VBO, 
  MESH_VERT_MERGE_INIT,
  MESH_VERT_MERGE_HASH,
  MESH_VERT_MERGE_REINDEX, 

  MESH_COLLECT_EDGE_ADJ_IBO,
  MESH_COLLECT_EDGE_ADJ_IBO_16BIT, 
  MESH_EDGE_ADJACENCY_INIT,
  MESH_EDGE_ADJACENCY_HASH,
  MESH_EDGE_ADJACENCY_FILL,

  MESH_WEDGE_FLOODING_ITER,
  MESH_WEDGE_FLOODING_FIRST_ITER_INIT, 
  MESH_WEDGE_FLOODING_LAST_ITER_COMPACTION,
  MESH_WEDGE_FLOODING_LAST_ITER_OUTPUT_FLAGS,

  MESH_SELECT_VERTS_FROM_SELECTED_EDGES,
  MESH_EXPAND_VERTS_FROM_SELECTED_EDGES,
  MESH_COMPACT_SELECTED_VERTS, 

  FILL_DISPATCH_ARGS_FILTERED_VERTS,
  FILL_DISPATCH_ARGS_FILTERED_EDGES,

  // DEPREACATED ----------------------
  MESH_FILTERING_EDGE_NORMAL, 
  MESH_FILTERING_EDGE_QUADRIC, 
  MESH_FILTERING_VERT_QUADRIC_INIT, 
  MESH_FILTERING_VERT_QUADRIC_DIFFUSION, 
  MESH_FILTERING_MOVE_VERTS,
  // ----------------------------------

  MESH_FILTER_VNOR_FILTERING, 

  MESH_FILTER_VPOS_FILTERING,
  MESH_FILTER_VPOS_FILTERING_FINISH,

  MESH_OP_SPLIT_EDGE_INIT, 
  MESH_OP_SPLIT_EDGE_COMPACT,
  FILL_DISPATCH_ARGS_SPLIT_EDGES,
  MESH_OP_SPLIT_EDGE_RESOLVE_CONFLICT, 
  MESH_OP_SPLIT_EDGE_EXECUTE,

  MESH_OP_COLLAPSE_EDGE_INIT,
  MESH_OP_COLLAPSE_EDGE_COMPACT,
  FILL_DISPATCH_ARGS_COLLAPSE_EDGES,
  MESH_OP_COLLAPSE_EDGE_RESOLVE_CONFLICT_0,
  MESH_OP_COLLAPSE_EDGE_RESOLVE_CONFLICT_1,
  MESH_OP_COLLAPSE_EDGE_RESOLVE_CONFLICT_2,
  MESH_OP_COLLAPSE_EDGE_EXECUTE,

  MESH_OP_FLIP_EDGE_INIT,
  MESH_OP_FLIP_EDGE_COMPACT,
  FILL_DISPATCH_ARGS_FLIP_EDGES,
  MESH_OP_FLIP_EDGE_VALIDATE,
  MESH_OP_FLIP_EDGE_RESOLVE_CONFLICT,
  MESH_OP_FLIP_EDGE_EXECUTE, 

  FILL_DISPATCH_ARGS_REMESHED_EDGES, 
  FILL_DISPATCH_ARGS_REMESHED_VERTS,

  MESH_ANALYSE_VERT_NORMAL,
  MESH_ANALYSE_VERT_NORMAL_VORONOIAREA,

  MESH_ANALYSE_VERT_CURV_PASS_0,
  MESH_ANALYSE_VERT_CURV_PASS_1,

  FILL_DRAW_ARGS_DBG_LINES,
  INDIRECT_DRAW_DBG_LINES, 


  // Testing GPGPU Primitives
  SCAN_TEST_UPSWEEP,
  SCAN_TEST_AGGREGATE,
  SCAN_TEST_DWSWEEP,

  SEGSCAN_TEST_UPSWEEP,
  SEGSCAN_TEST_AGGREGATE,
  SEGSCAN_TEST_DWSWEEP,

  CONV1D_TEST_BUILD_PATCH,
  CONV1D_TEST_CONVOLUTION,

  LISTRANKING_INIT_ANCHORS,
  LISTRANKING_COMPACT_ANCHORS,
  LISTRANKING_SPLICE_OUT_NODES,
  LISTRANKING_FILL_DISPATCH_ARGS,
  LISTRANKING_SUBLIST_POINTER_JUMPING,
  LISTRANKING_LOOPED_POINTER_JUMPING,
  LISTRANKING_MARK_LOOP_HEAD_TAIL,
  LISTRANKING_RELINKING,
  LISTRANKING_LOOPED_RELINKING,
  LISTRANKING_SETUP_INPUTS,
  LISTRANKING_OUTPUT_DATA, 

  MAX_SHADER_TYPE,
};

/**
 * Shader module. shared between instances.
 */
class StrokeGenShaderModule {
 private:
  std::array<GPUShader *, MAX_SHADER_TYPE> shaders_;

  /** Shared shader module across all engine instances. */
  static StrokeGenShaderModule *g_shader_module;

 public:
  StrokeGenShaderModule();
  ~StrokeGenShaderModule();

  GPUShader *static_shader_get(eShaderType shader_type);
  // TODO: GPUMaterial ? (see impl in eevee)


  /** Only to be used by Instance constructor. */
  static StrokeGenShaderModule *module_get();
  static void module_free();

 private:
  const char *static_shader_create_info_name_get(eShaderType shader_type);
};

}  // namespace blender::bnpr
