/* SPDX-License-Identifier: GPL-2.0-or-later
 * Copyright 2021 Blender Foundation.
 */

/** \file
 * \ingroup bnpr
 *
 * Shader module that manage shader libraries, deferred compilation,
 * and static shader usage.
 */

#pragma once

#include <array>
#include <string>

#include "BLI_string_ref.hh"
#include "DRW_render.hh"
#include "GPU_material.hh"
#include "GPU_shader.hh"


namespace blender::npr::strokegen {

/* Keep alphabetical order and clean prefix. */
enum eShaderType {
  DEPTH = 0,
  POINTCLOUD_DEPTH,
  CURVES_DEPTH,
  DEPTH_CONSERVATIVE,
  POINTCLOUD_DEPTH_CONSERVATIVE,

  // Process Contours in current mesh
  GPU_MESHING_BOOSTRAP,
  CONTOUR_GEOM_EXTRACT,
  CONTOUR_GEOM_EXTRACT_IBO_16BIT,
  FILL_DISPATCH_ARGS_CONTOUR_EDGES,
  FILL_DISPATCH_ARGS_CONTOUR_VERTS,
  FILL_DISPATCH_ARGS_CONTOUR_FRAGS,
  FILL_DISPATCH_ARGS_CONTOUR_2D_SAMPLES, 
  EXTRACT_CURRENT_MESH_CONTOUR_DATA,

  // Process all contours
  CLEAR_FRAG_TO_CONTOUR_IDMAPPING,
  PREP_FRAG_TO_CONTOUR_IDMAPPING,
  FINISH_FRAG_TO_CONTOUR_IDMAPPING,
  CONTOUR_FRAG_VISIBILITY_TEST,
  CONTOUR_FRAG_SETUP_VISIBILITY_SEGMENTATION,
  CONTOUR_VISIBILITY_SPLIT_STEP_0,
  CONTOUR_VISIBILITY_SPLIT_STEP_1,
  CONTOUR_VISIBILITY_SPLIT_STEP_2,
  CONTOUR_VISIBILITY_SPLIT_STEP_3,

  FILL_CONTOUR_EDGE_RANKING_INPUTS,

  SERIALIZE_RANKED_CONTOUR_EDGES,
  SETUP_CONTOUR_SEGMENTATION,
  FINISH_CONTOUR_SEGMENTATION,

  RECORD_TEMPORAL_CONTOUR_DATA, 

  CALC_CONTOUR_EDGES_DRAW_DATA,


  CONTOUR_ARCLEN_PARAMETERIZATION,
  CONTOUR_ALLOC_2D_SAMPLES,
  CONTOUR_ALLOC_2D_SAMPLES_FINISH,
  CLEAR_2D_SAMPLE_TO_CONTOUR_IDMAPPING,
  PREP_2D_SAMPLE_TO_CONTOUR_IDMAPPING,
  FINISH_2D_SAMPLE_TO_CONTOUR_IDMAPPING,
  CONTOUR_2D_SAMPLES_EVAL_POSITION,
  CONTOUR_2D_SAMPLES_EVAL_TOPO_STEP_0,
  CONTOUR_2D_SAMPLES_SEGMENTATION_PREP_SEGTAILS,
  CONTOUR_2D_SAMPLES_EVAL_TOPO_SETUP_SEGSCAN,
  CONTOUR_2D_SAMPLES_EVAL_TOPO_FINISH_SEGSCAN,
  CONTOUR_2D_SAMPLES_REJECT_FAKE_CORNERS,
  CONTOUR_2D_SAMPLES_CALC_RENDER_DATA, 

  // Contour Drawers
  FILL_DRAW_ARGS_CONTOUR_EDGES,
  FILL_DRAW_ARGS_CONTOUR_2D_SAMPLES,
  FILL_DRAW_ARGS_REMESHED_SURFACE_DEPTH,

  INDIRECT_DRAW_CONTOUR_MESH_DEPTH, 
  INDIRECT_DRAW_CONTOUR_EDGES,
  INDIRECT_DRAW_CONTOUR_2D_SAMPLES, 

  // Contour Pixel Extraction (WIP)
  CONTOUR_PIXEL_COMPRESS,
  CONTOUR_PIXEL_COMPRESS_DBG,

  // GPU Meshing Experiment
  MESH_COLLECT_VBO, 
  MESH_VERT_MERGE_INIT,
  MESH_VERT_MERGE_HASH,
  MESH_VERT_MERGE_REINDEX, 

  MESH_COLLECT_EDGE_ADJ_IBO,
  MESH_COLLECT_EDGE_ADJ_IBO_16BIT, 
  MESH_EDGE_ADJACENCY_INIT,
  MESH_EDGE_ADJACENCY_HASH,
  MESH_EDGE_ADJACENCY_HASH_FINISH,
  MESH_EDGE_ADJACENCY_FILL,

  MESH_WEDGE_FLOODING_ITER,
  MESH_WEDGE_FLOODING_FIRST_ITER_INIT, 
  MESH_WEDGE_FLOODING_LAST_ITER_COMPACTION,
  MESH_WEDGE_FLOODING_LAST_ITER_OUTPUT_FLAGS,

  MESH_WEDGE_MARK_EDGES_ON_SELECTION_BORDER, 

  MESH_SELECT_VERTS_FROM_SELECTED_EDGES,
  MESH_EXPAND_VERTS_FROM_SELECTED_EDGES,
  MESH_COMPACT_SELECTED_VERTS, 

  FILL_DISPATCH_ARGS_FILTERED_VERTS,
  FILL_DISPATCH_ARGS_FILTERED_EDGES,

  MESH_FILTER_VNOR_FILTERING, 
  MESH_FILTER_VPOS_FILTERING, 
  MESH_FILTER_VQUADRIC_DIFFUSION,
  MESH_FILTER_QUADRIC_VPOS_FILTERING,
  MESH_FILTER_SUBDIV_VPOS_SMOOTH,
  MESH_FILTER_SUBDIV_VPOS_SMOOTH_FINISH,
  MESH_FILTER_LOOP_SUBDIV_EDGE_POINTS, 
  MESH_FILTER_VCURV_SMOOTHING,
  MESH_FILTER_VCURV_SMOOTHING_OUTPUT_REMESH_LEN, 

  MESH_OP_SPLIT_EDGE_INIT, 
  MESH_OP_SPLIT_EDGE_COMPACT,
  FILL_DISPATCH_ARGS_SPLIT_EDGES,
  MESH_OP_SPLIT_EDGE_EXCLUDE_BORDER, 
  MESH_OP_SPLIT_EDGE_RESOLVE_CONFLICT, 
  MESH_OP_SPLIT_EDGE_EXECUTE,

  MESH_OP_COLLAPSE_EDGE_INIT,
  MESH_OP_COLLAPSE_EDGE_COMPACT,
  FILL_DISPATCH_ARGS_COLLAPSE_EDGES,
  MESH_OP_COLLAPSE_EDGE_RESOLVE_CONFLICT_0,
  MESH_OP_COLLAPSE_EDGE_RESOLVE_CONFLICT_1,
  MESH_OP_COLLAPSE_EDGE_RESOLVE_CONFLICT_2,
  MESH_OP_COLLAPSE_EDGE_EXECUTE,

  MESH_OP_FLIP_EDGE_INIT,
  MESH_OP_FLIP_EDGE_COMPACT,
  FILL_DISPATCH_ARGS_FLIP_EDGES,
  MESH_OP_FLIP_EDGE_VALIDATE,
  MESH_OP_FLIP_EDGE_RESOLVE_CONFLICT,
  MESH_OP_FLIP_EDGE_EXECUTE,

  MESH_OP_SPLIT_FACE_INIT,
  MESH_OP_SPLIT_FACE_GENERATE_WORKS,
  FILL_DISPATCH_ARGS_SPLIT_FACES,
  MESH_OP_SPLIT_FACE_EXECUTE, 

  FILL_DISPATCH_ARGS_REMESHED_EDGES, 
  FILL_DISPATCH_ARGS_REMESHED_VERTS,

  MESH_ANALYSE_VERT_NORMAL,
  MESH_ANALYSE_VERT_NORMAL_VORONOIAREA,
  MESH_ANALYSE_VERT_NORMAL_TOPOFLAGS,
  MESH_ANALYSE_VERT_NORMAL_VORONOIAREA_TOPOFLAGS,
  MESH_ANALYSE_EDGE_FEATURES,

  MESH_ANALYSE_VERT_CONTOUR_GRADIENT, 

  MESH_ANALYSE_VERT_CURV_PASS_0,
  MESH_ANALYSE_VERT_CURV_PASS_1_RUSINKIEWICZ,
  MESH_ANALYSE_VERT_CURV_PASS_1_JACQUES,

  MESH_LOOP_SUBD_TREE_BUILD_NODES_UPWARDS_FOR_FACE_EDGES,
  MESH_LOOP_SUBD_TREE_INIT_NODES_DOWNWARDS,
  MESH_LOOP_SUBD_TREE_BUILD_NODES_DOWNWARDS,

  MESH_COMPACT_NEW_TEMPORAL_RECORDS,
  MESH_CALCULATE_NEW_TEMPORAL_RECORDS,
  MESH_RECONSTRUCT_OLD_TEMPORAL_RECORDS, 
  FILL_DISPATCH_ARGS_TEMPORAL_RECORDS,

  FILL_DRAW_ARGS_DBG_LINES,
  INDIRECT_DRAW_DBG_LINES, 


  // GPGPU Primitives
  SCAN_TEST_UPSWEEP,
  SCAN_TEST_AGGREGATE,
  SCAN_TEST_DWSWEEP,

  SCAN_UINT_ADD_UPSWEEP,
  SCAN_UINT_ADD_AGGREGATE,
  SCAN_UINT_ADD_DWSWEEP,

  SEGSCAN_TEST_UPSWEEP,
  SEGSCAN_TEST_AGGREGATE,
  SEGSCAN_TEST_DWSWEEP,

  SEGSCAN_UINT_ADD_UPSWEEP,
  SEGSCAN_UINT_ADD_AGGREGATE,
  SEGSCAN_UINT_ADD_DWSWEEP,

  SEGSCAN_FLOAT_ADD_UPSWEEP,
  SEGSCAN_FLOAT_ADD_AGGREGATE,
  SEGSCAN_FLOAT_ADD_DWSWEEP, 

  SEGSCAN_UINT_MIN_UPSWEEP,
  SEGSCAN_UINT_MIN_AGGREGATE,
  SEGSCAN_UINT_MIN_DWSWEEP,

  SCAN_FILL_DISPTACH_ARGS, 

  CONV1D_TEST_BUILD_PATCH,
  CONV1D_TEST_CONVOLUTION,
  CONV1D_SEG_DENOISE_BUILD_PATCH,
  CONV1D_SEG_DENOISE_CONVOLUTION,
  CONV1D_2D_SAMPLE_BUILD_PATCH,
  CONV1D_2D_SAMPLE_CORNER_CONVOLUTION_STEP_0,
  CONV1D_2D_SAMPLE_CORNER_CONVOLUTION_STEP_1,
  CONV1D_2D_SAMPLE_CALC_TANGENT_CURVATURE,
  CONV1D_2D_SAMPLE_DENOISE_VISIBILITY, 

  CONV1D_FILL_DISPATCH_ARGS, 

  LISTRANKING_INIT_ANCHORS,
  LISTRANKING_COMPACT_ANCHORS,
  LISTRANKING_SPLICE_OUT_NODES,
  LISTRANKING_FILL_DISPATCH_ARGS,
  LISTRANKING_SUBLIST_POINTER_JUMPING,
  LISTRANKING_LOOPED_POINTER_JUMPING,
  LISTRANKING_MARK_LOOP_HEAD_TAIL,
  LISTRANKING_RELINKING,
  LISTRANKING_LOOPED_RELINKING,
  LISTRANKING_SETUP_INPUTS,
  LISTRANKING_OUTPUT_DATA_PASS_0,
  LISTRANKING_OUTPUT_DATA_PASS_1, 

  MAX_SHADER_TYPE,
};

/**
 * Shader module. shared between instances.
 */
class StrokeGenShaderModule {
 private:
  std::array<GPUShader *, MAX_SHADER_TYPE> shaders_;

  /** Shared shader module across all engine instances. */
  static StrokeGenShaderModule *g_shader_module;

 public:
  StrokeGenShaderModule();
  ~StrokeGenShaderModule();

  GPUShader *static_shader_get(eShaderType shader_type);
  // TODO: GPUMaterial ? (see impl in eevee)


  /** Only to be used by Instance constructor. */
  static StrokeGenShaderModule *module_get();
  static void module_free();

 private:
  const char *static_shader_create_info_name_get(eShaderType shader_type);
};

}  // namespace blender::bnpr
