name: Ubuntu

on:
  #push:
    #branches: [ master ]
  #schedule:
  #  - cron: 0 0 * * 1
  pull_request:
    branches: [ master ]

permissions: {}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: configure
      run: |
        sudo apt update
        sudo apt install build-essential git subversion cmake libx11-dev libxxf86vm-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libegl-dev libepoxy-dev
        sudo apt install libwayland-dev wayland-protocols libxkbcommon-dev libdbus-1-dev linux-libc-dev

    - name: Fetch source & libs
      run: |
        mkdir ~/bforartistsrepo
        cd ~/bforartistsrepo
        git clone https://github.com/Bforartists/Bforartists
        cd ~/bforartistsrepo/Bforartists
        make update
        ./build_files/build_environment/install_linux_packages.py --all
    
    - name: Build
      run: |
        cd ~/bforartistsrepo/Bforartists
        make

    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: Bforartists-Release-${{ runner.os }}
        path: /home/runner/bforartistsrepo/bfa_build_linux/bin/

