name: Windows
on:
  push:
      branches: [ "pull-npr-texure-sockets" ]
  pull_request:
      branches: [ "pull-npr-texure-sockets" ]

jobs:
  build:
    uses: ./.github/workflows/nightly-build.yml
    with:
      os: "windows-latest"
      c_compiler: "cl"
      cpp_compiler: "cl"
