name: Windows

on:
  pull_request:
    branches: [ dev ]

permissions: {}
jobs:
  build:
    runs-on: windows-latest
    env:
      BUILD_FOLDER: ${{ github.workspace }}
      CONFIG : lite
      LIB_CACHE : ${{ github.workspace }}/../lib

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3
    #   run: |
    #    cd ~\bforartistsrepo
    #    git clone -b work-sequencer https://github.com/zNightlord/Bforartists.git
    - name: Make Dir
      run: |
        mkdir 'D:\a\Bforartists\lib'
    - name: Cache library
      env:
        cache-name: ${{ github.ref }}
      uses: actions/cache@v3
      with:
        path: ${{ env.LIB_CACHE }}
        key: lib
    - name: Svn lib
      run: |
        cd ..\lib
        svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc15/
    # - name: Make
    #   run: |
    #    cd ..\Bforartists
    #    .\make.bat ninja ${{ env.CONFIG }}
    - name: Show dir
      run: |
        cd ..
        dir
        cd lib
        dir
        cd ..\Bforartists
        dir
    # - name: Upload Build
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: Bforartists-Release-${{ runner.os }}
    #     path: C:/Users/runneradmin/bforartistsrepo/bfa_build_windows*_x64_vc17*/bin
