name: Windows

on:
  push:
    branches: [ windows-workflow ]
  #schedule:
  #  - cron: 0 0 * * 1
  #pull_request:
  #  branches: [ master ]

permissions: {}
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Clone, get libraries
      run: |
        mkdir ~\bforartistsrepo
        cd ~\bforartistsrepo
        git clone -b windows-workflow https://github.com/zNightlord/Bforartists
        dir
        cd ~\bforartistsrepo\Bforartists
        make update
        git submodule update --init --progress lib/windows_x64
        cd lib\windows_x64
        dir
        git pull
        dir
        
    - name: Build
      if: success() || failure()
      run: |
        cd ~\bforartistsrepo\Bforartists
        gir fetch origin b3.6
        git checkout b3.6
        .\make.bat ninja release
        dir
        cd ~\bforartistsrepo
        dir
    - name: Build 2
      if: success() || failure()
      run: |
        cd ~\bforartistsrepo\Bforartists
        .\make.bat ninja lite
        dir


    - name: Upload Build
      if: success() || failure()
      uses: actions/upload-artifact@v2
      with:
        name: Bforartists-Release-${{ runner.os }}
        path: C:/Users/runneradmin/bforartistsrepo/bfa_build_windows_Release_x64_vc16_Release/bin
