name: Windows

on:
  push:
    branches: [ pull-npr-texure-sockets ]
  # schedule:
  #   - cron: 0 0 * * 1
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:

permissions: {}
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: make
      shell: cmd
      run: |
        mkdir C:/Users/runneradmin/bforartistsrepo
        cd C:/Users/runneradmin/bforartistsrepo
        git clone -b pull-npr-texure-sockets https://github.com/zNightlord/Bforartists
        cd Bforartists
        python ./build_files/utils/make_update.py
        make
        dir
        cd ..
        dir


    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: Bforartists-Release-${{ runner.os }}
        path: | 
          C:/Users/runneradmin/bforartistsrepo/bfa_build_windows_x64_vc17_Release/bin
          D:/a/Bforartists/Bforartists/bfa_build_windows_x64_vc17_Release/bin