name: Windows

on:
  # push:
  #  branches: [ workflow-fix ] # ignore this for testing purposes
  # schedule:
  #   - cron: 0 0 * * 1
  pull_request:
     branches: [ workflow-fix ]
  workflow_dispatch:

permissions: {}
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: make
      shell: cmd
      run: |
        mkdir C:/Users/runneradmin/bforartistsrepo
        cd C:/Users/runneradmin/bforartistsrepo
        git clone https://github.com/Bforartists/Bforartists
        cd Bforartists
        python ./build_files/utils/make_update.py
        make lite
        dir
        cd ..
        dir


    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: Bforartists-Release-${{ runner.os }}
        path: |
          C:/Users/runneradmin/bforartistsrepo/bfa_build_windows_*_x64_vc*/bin
          D:/a/Bforartists/Bforartists/bfa_build_windows_*_x64_vc*/bin
        
