name: windows

on:
  push:
    branches: [ dev-build ]

permissions: {}
jobs:
  build:
    runs-on: windows-latest
    env:
      CONFIG : lite

    steps:
    - name: Clone Repository
      # uses: actions/checkout@v4
      run: |
       mkdir ~\Bforartists
       cd ~\Bforartists
       git clone https://github.com/zNightlord/Bforartists.git
       cd Bforartists
       git config --global --add safe.directory C:\Users\runneradmin\Bforartists\Bforartists
       git config --global user.email "you@example.com"
       git config --global user.name "Your Name"
       git fetch
       git checkout bforartists-juniper
     # git checkout dev-work
     # git merge origin/custom-wire-color
     # git merge origin/toolbar-assetshelf
     # git merge origin/comp-tex-coord
     # git merge origin/anim-motion-curve
     # git merge origin/draw-nla   
     # git clone -b work-sequencer https://github.com/zNightlord/Bforartists.git
    # - name: Cache library
    #   uses: actions/cache@v3
    #   with:
    #     key: windows
    #     path: |
    #       C:\Users\runneradmin\Bforartists\lib
    #       !C:\Users\runneradmin\Bforartists\Bforartists
    - name: Svn library
      run: |
        if (!(test-path "C:\Users\runneradmin\Bforartists\lib\")) {
          mkdir ~\Bforartists\lib
          cd ~\Bforartists\lib
          svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc15/
        } else {
          cd ~\Bforartists\lib\win64_vc15
          svn update
          cd ..
        }
    - name: Make
      run: |
       cd ~\Bforartists\Bforartists\source\blender
       dir
       cd ~\Bforartists\Bforartists
       .\make.bat ninja ${{ env.CONFIG }}
    - name: Make 2
      if: success() || failure()
      run: |
        cd ~\Bforartists\Bforartists
        .\make.bat ninja ${{ env.CONFIG }}
    - name: Show dir
      run: |
        cd ~\Bforartists
        dir
        cd lib\win64_vc15
        dir
        cd ..\..\Bforartists
        dir
    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: Bforartists-${{ env.CONFIG }}-${{ runner.os }}-${{ github.head_ref }}
        path: C:/Users/runneradmin/Bforartists/*_build_windows_*_x64_vc1*/bin
