name: windows

on:
  pull_request:
    branches: [ dev ]

permissions: {}
jobs:
  build:
    runs-on: windows-latest
    env:
      CONFIG : lite

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
    #   run: |
    #    cd ~\bforartistsrepo
    #    git clone -b work-sequencer https://github.com/zNightlord/Bforartists.git
    - name: Cache library
      uses: actions/cache@v3
      with:
        key: windows
        path: |
          D:\a\Bforartists\*
          !D:\a\Bforartists\Bforartists
    - name: Svn library
      run: |
        if (!(test-path "D:\a\Bforartists\lib\")) {
          mkdir 'D:\a\Bforartists\lib'
          cd ..\lib
          svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc15/
        } else {
          cd ..\lib\win64_vc15
          svn update
          cd ..
        }
    - name: Make
      run: |
       cd ..\Bforartists
       .\make.bat ninja ${{ env.CONFIG }}
    - name: Show dir
      run: |
        cd ..
        dir
        cd lib\win64_vc15
        dir
        cd ..\..\Bforartists
        dir
    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: Bforartists-${{ env.CONFIG }}-${{ runner.os }}-${{ github.head_ref }}
        path: D:/a/Bforartists/bfa_build_windows_*_x64_vc1*/bin
